# Generated by Django 4.2.7 on 2023-11-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_character_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answerOne', models.CharField(max_length=30)),
                ('answerTwo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.CharField(max_length=40),
        ),
    ]
