# Generated by Django 4.2.7 on 2023-11-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_answer_delete_answers_rename_questions_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerOne',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answerTwo',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerOne',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answerTwo',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
